GMAIL_USERNAME: 'ducbm@zigexn.vn'
GMAIL_PASSWORD: 'minhDUC02091995'

aws_access_key_id: 'AKIAIAJR65JO6EIPQWTA'
aws_secret_access_key: '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'
associate_tag: 'microv'

api_key: '126339711758862'
api_secret: '3goOcTtZXUQvZQhEgj8g-hzlOds'
cloud_name: 'dcmwhmyzp'
